import { MacroCategory } from './types';

export const MACROS: Record<MacroCategory, { color: string; cls: string }> = {
  Besoins:             { color: '#3B82F6', cls: 'b-B' },
  Envies:              { color: '#F59E0B', cls: 'b-E' },
  Épargne:             { color: '#10B981', cls: 'b-Ep' },
  Revenus:             { color: '#8B5CF6', cls: 'b-R' },
  'Virements internes':{ color: '#64748B', cls: 'b-VI' },
  'Non classé':        { color: '#6B7280', cls: 'b-N' },
};

export const SUBS: Record<string, string[]> = {
  Besoins:  ['alimentation de base','transports/voiture','assurances','prêts immo','factures énergie/eau','santé','famille','cantine','frais bancaires','ménage','frais notaire','travaux/jardin'],
  Envies:   ['sorties resto/WE','shopping','vacances/WE en famille','abonnements sports','abonnements divertissements','courses non essentielles'],
  Épargne:  ['épargne'],
  Revenus:  ['salaires','remboursements','CAF'],
  'Virements internes': ['virement interne'],
};

export const SUB2MACRO: Record<string, MacroCategory> = {};
Object.entries(SUBS).forEach(([m, ss]) =>
  ss.forEach(s => (SUB2MACRO[s] = m as MacroCategory))
);

export const ALL_SUBS = Object.values(SUBS).flat();

export const ACCOUNT_COLORS: Record<string, string> = {
  'CB Yann':                '#3B82F6',
  'CB Chloé':               '#EC4899',
  'Compte commun Fortuneo': '#10B981',
  'Compte SG':              '#F59E0B',
};

export const MERCHANT_RULES: Record<string, string> = {
  "PLAYBAC": "abonnements divertissements",
  "IMPÔTS": "frais bancaires",
  "BIP & GO": "transports/voiture",
  "ALLIANZ I A R D ALLIANZ I A R D": "assurances",
  "ANTARIUS": "frais bancaires",
  "MULT IMPACT": "assurances",
  "GC RE LUKO COVER": "assurances",
  "CLIMYM MAINTENANCE 10 03": "factures énergie/eau",
  "ALEXIS LELOUCY 10 03": "vacances/WE en famille",
  "FREE": "abonnements divertissements",
  "PAJEMPLOI": "salaires",
  "PRÊT IMMO": "prêts immo",
  "SOGESSUR": "assurances",
  "PAIEMENT ROSA": "ménage",
  "ASSMAT": "famille",
  "CAF DU RHONE": "salaires",
  "EAU DU GRAND LYON": "factures énergie/eau",
  "URSSAF CESU": "ménage",
  "SFR": "abonnements divertissements",
  "ALLIANZ": "assurances",
  "LUKO": "assurances",
  "SUEZ EAU FRANCE SAS-SUEZ EAU FRANCE": "factures énergie/eau",
  "CRECHE": "famille",
  "DEEZERFR": "abonnements divertissements",
  "APPLE.COM/BILL": "abonnements divertissements",
  "TCL LYON": "transports/voiture",
  "NETFLIX.COM": "abonnements divertissements",
  "CAMIEG": "santé",
  "EDF CLIENTS PARTICULIERS": "factures énergie/eau",
  "ASSURANCE VIE SUZANNE": "épargne",
  "ASSURANCE VIE JEANNE": "épargne",
  "ASSURANCE VIE GASPARD": "épargne",
  "SWILE": "cantine",
  "AMAZON PAYMENTS": "shopping",
  "SNCF": "transports/voiture",
  "IKEA": "ménage",
  "AXA FRANCE": "santé",
  "AXA ASS VIE": "santé",
  "MUTUELLE AXA": "santé",
  "ENERGIE MUTUELLE": "santé",
  "CPAM": "santé",
  "VIREMENT AVEC FORTUNEO LDDS": "épargne",
  "VIREMENT AVEC FORTUNEO LIVRE": "épargne",
  "VIREMENT EPARGNE LDDS": "épargne",
  "AMAZON PRIME": "abonnements divertissements",
  "NETFLIX COM": "abonnements divertissements",
  "DEEZER SA": "abonnements divertissements",
  "PRIME VIDEO": "abonnements divertissements",
  "LUNII SAS": "abonnements divertissements",
  "BITWARDEN": "abonnements divertissements",
  "TENACY": "salaires",
  "RTE RESEAU DE TRANSPORT D EL": "salaires",
  "DGFIP FINANCES PUBLIQUES": "salaires",
  "EPARGNE": "épargne",
  "REVOLUT": "épargne",
  "SOLDE REGLEMENTAIRE LIVRET A": "épargne",
  "VERSEMENT INITIAL LDD": "épargne",
  "REMBOURSEMENT VACANCES": "épargne",
  "REMBOURSEMENT CANADA": "épargne",
  "DIRECTION GENERALE DES FINA": "factures énergie/eau",
  "EDF CLT PART": "factures énergie/eau",
  "EAU GRAND LYON": "factures énergie/eau",
  "ENTRETIEN POMPE A CHAL": "factures énergie/eau",
  "ECHEANCE PRET": "prêts immo",
  "RECU DE: SARL NOTAIRES FOCH": "frais notaire",
  "NOTAIRES DBTB": "frais notaire",
  "FRAIS VIREMENT": "frais bancaires",
  "COTISATION QUIETIS": "frais bancaires",
  "TIMBRE FISCAL": "frais bancaires",
  "F COTISATION A UNE OFFRE D ASSURANCE": "assurances",
  "URSSAF": "famille",
  "KINOUGARDE": "famille",
  "MJC": "famille",
  "VILLE DE LYON": "famille",
  "SIGPAS": "famille",
  "REST SCOL CB NET": "famille",
  "GOUJON CHLOE": "famille",
  "NATH BOUDON": "famille",
  "SOLDE TOUS COMPTES NATH": "famille",
  "TOP-ASSMAT": "famille",
  "TOP ASSMAT": "famille",
  "NOUNOU-TOP": "famille",
  "SJR LABELS": "famille",
  "LUMYS PHOTO": "famille",
  "AMAZON EU SARL": "shopping",
  "AMZN MKTP FR": "shopping",
  "AMAZON.FR": "shopping",
  "VINTED": "shopping",
  "LEBONCOIN": "remboursements",
  "VEEPEE": "shopping",
  "KLARNA": "shopping",
  "LA REDOUTE": "shopping",
  "DECATHLON": "shopping",
  "FNAC": "shopping",
  "LEROY MERLIN": "ménage",
  "CASTORAMA": "travaux/jardin",
  "IKKS PARIS": "shopping",
  "SEZANE": "shopping",
  "ASPHALTE": "shopping",
  "PICARD SURGELES": "alimentation de base",
  "LA VIE CLAIRE": "alimentation de base",
  "LIDL": "alimentation de base",
  "INTERMARCHE": "alimentation de base",
  "AUCHAN": "alimentation de base",
  "CARREFOUR": "alimentation de base",
  "MONOPRIX": "shopping",
  "UBER *TRIP": "transports/voiture",
  "DOTT SCOOTER": "transports/voiture",
  "RATP": "transports/voiture",
  "KEOLIS LYON": "transports/voiture",
  "SPL MOBILITES": "transports/voiture",
  "3X 4X ONEY": "transports/voiture",
  "TRAINLINE": "transports/voiture",
  "AIRBNB": "vacances/WE en famille",
  "AIR CAN": "vacances/WE en famille",
  "BOOKING": "vacances/WE en famille",
  "SARL M FIT CENTER": "abonnements sports",
  "CROSSIFT": "abonnements sports",
  "SAS SAS 4M LYON": "alimentation de base",
  "LAURENT DAUTRIA LYON": "santé",
  "DR DANTEC ADRIE LYON": "santé",
  "GD PHIE MONTCHAT LYON": "santé",
  "L ENCHANTEMENT LYON": "shopping",
  "VIR CAMIEG": "salaires",
  "TERRES LYONNAISE LYON 3EME": "alimentation de base",
  "PRLV DEEZERFR": "abonnements divertissements",
  "MAISON THEILLER LYON 3EME": "alimentation de base",
  "LES SAVEURS ST E COLOMBIER SAU": "alimentation de base",
  "LA FERME DU JARI THURINS": "alimentation de base",
  "NAVARRO STEPHANE MEYZIEU": "alimentation de base",
  "CBMDISTRIBUTION VAULNAVEYS LE": "transports/voiture",
  "BOULANGERIE MON LYON": "alimentation de base",
  "LES COULEURS DU LYON": "shopping",
  "MRS RA 262 SAINT CYR AU": "cantine",
  "VIR AXA FRANCE VIE": "santé",
  "VIR DGFIP FINANCES PUBLIQUES": "salaires",
  "LA LIB. DU COURS LYON": "shopping",
  "VALERIE GIRAUD NEUVILLE SUR": "alimentation de base",
  "PRLV MULT IMPACT": "assurances",
  "NETFLIX COM PARIS": "abonnements divertissements",
  "VILLE DE LYON LYON CEDEX 01": "famille",
  "VIR PAJEMPLOI": "salaires",
  "PATISS JACQUIER LYON": "alimentation de base",
  "PRLV KINOUGARDE": "famille",
  "NOUNOU-TOP E14 9NN LO 11,98 EUR": "famille",
  "VIR CAF DU RHONE": "salaires",
  "LEBONCOIN PARIS": "shopping",
  "MGP*VINTED 0 VILNIUS": "shopping",
  "DECATHLON 0121 BRON": "shopping",
  "PICARD SURGELES LYON 3EME": "alimentation de base",
  "FROMAGER DE MONT LYON": "alimentation de base",
  "VIR ASSURANCE VIE SUZANNE": "épargne",
  "VIR ASSURANCE VIE JEANNE": "épargne",
  "VIR ASSURANCE VIE GASPARD": "épargne",
  "VIREMENT ASSMAT": "famille",
  "PRLV EDF CLIENTS PARTICULIERS": "factures énergie/eau",
  "PIERRE ET MARCEL LYON": "alimentation de base",
  "IKEA VENISSIEUX VENISSEUX": "shopping",
  "SYNDICAT LOCAL LES DEUX ALPE": "vacances/WE en famille",
  "PRLV DIRECTION GENERALE DES FINA": "factures énergie/eau",
  "VIR EPARGNE CHLOE": "épargne",
  "VIR RTE RESEAU DE TRANSPORT D EL": "salaires",
  "CARREFOURMARKET BAGNOLS SUR C": "alimentation de base",
  "COMPTOIR BOULAN BAGNOLS SUR C": "alimentation de base",
  "VIR CPAM RHONE": "salaires",
  "VOISIN LYON 9EME": "shopping",
  "PATISSERIE JACQU LYON": "alimentation de base",
  "CHARMILLES LYON": "santé",
  "KEOLIS LYON LYON": "transports/voiture",
  "CLC STUDIO LYON": "shopping",
  "MAISON BALL BRON": "alimentation de base",
  "U EXPRESS 69 LYON": "alimentation de base",
  "SINABRO LYON EME": "sorties resto/WE",
  "L ARTCHIMISTE LYON EME": "sorties resto/WE",
  "VIR ENERGIE MUTUELLE": "santé",
  "MONTCYCLE LYON": "transports/voiture",
  "VIR EDF CLT PART RBT SCT": "factures énergie/eau",
  "VIR EPARGNE": "épargne",
  "LA REDOUTE ROUBAIX": "shopping",
  "PRLV EAU GRAND LYON": "factures énergie/eau",
  "KING JOUET BAGNOLS SUR C": "shopping",
  "HPY*OIA-16BAGNOL BAGNOLS SCEZE": "shopping",
  "INTERMARCHE BAGNOLS SUR C": "alimentation de base",
  "VIREMENT MJC": "famille",
  "APPLE.COM/BILL ITUNES.COM": "abonnements divertissements",
  "REST SCOL CB NET 69 LYON": "famille",
  "PPG*LABELLEBOUCL LYON": "shopping",
  "FRAIS VIR INSTANTANE ELEC REF": "frais bancaires",
  "CARREFOUR CITY LYON": "alimentation de base",
  "DR DANTEC LYON": "santé",
  "PRELEVEMENT EUROPEEN DE: ANTARIUS ID: FR18ZZZ427359 MOTIF: ANTA": "frais bancaires",
  "NETFLIX.COM PARIS": "abonnements divertissements",
  "STATION AVIA NERONDE": "transports/voiture",
  "LA REDOUTE 59100 ROUBAIX": "shopping",
  "PRELEVEMENT EUROPEEN DE: GC RE LUKO COVER ID: DE5622200002197951 MOTIF: REF-9C03ECB5A8F276C60F": "assurances",
  "PRELEVEMENT EUROPEEN DE: FREE TELECOM ID: FR83ZZZ459654 MOTIF: FREE HAUTDEBIT": "abonnements divertissements",
  "PRELEVEMENT EUROPEEN DE: SOGESSUR ID: FR13ZZZ428225 MOTIF: SOGESSUR//0": "assurances",
  "PRELEVEMENT EUROPEEN DE: SOGESSUR ID: FR13ZZZ428225 MOTIF: SOGESSUR//+": "assurances",
  "STATION AVIA BRON": "transports/voiture",
  "SUPERETTE MONCHA LYON": "alimentation de base",
  "APPLE.COM/BILL CORK": "abonnements divertissements",
  "VIR VIREMENT AVEC FORTUNEO COMPT": "virement interne",
  "SNCF-VOYAGEURS PARIS 10": "sorties resto/WE",
  "PRINTEMPS LYON 2": "shopping",
  "COT' ET VIANDE TAPONAS": "alimentation de base",
  "CARTA'JEU LYON 7EME": "shopping",
  "VESSIERE MONTCH LYON": "alimentation de base",
  "LA POSTE L699270 LYON MONTCHAT": "shopping",
  "SNCF INTERNET PARIS 10": "transports/voiture",
  "PHIE DE CONNAUX CONNAUX": "santé",
  "PONCET PATRICK IRIGNY": "alimentation de base",
  "LES GLOUGLOUTONS LYON": "sorties resto/WE",
  "AIR CAN014210475 PARIS": "vacances/WE en famille",
  "VIREMENT NATH BOUDON FIN CONTRAT": "famille",
  "VIR SOLDE NATH CONGES PAYES": "famille",
  "VIR SOLDE TOUT COMPTE NATH": "famille",
  "VIR VIREMENT AVEC FORTUNEO": "virement interne",
  "VEEPEE SAINT-DENIS": "shopping",
  "AMAZON PAYMENTS PARIS": "shopping",
  "VAL D'OUEST VEND ECULLY": "santé",
  "BOUCHERIE 3E LYON": "alimentation de base",
  "OPTIQUE MONTCHAT LYON 3EME": "santé",
  "DR PIERRILLAS ECULLY": "santé",
  "MOI FLEXITARIEN LYON": "sorties resto/WE",
  "POINT VISION 8 LYON 8EME": "santé",
  "VIR TENACY": "salaires",
  "MEDICINA GESTION FONTAINES SUR": "santé",
  "BISTROT BERTHET LYON": "cantine",
  "AMAZON PAYMENTS PAYLI2441535/": "shopping",
  "PATISSERIE JACQU LYON EME": "alimentation de base",
  "DOTT SCOOTER RID AMSTERDAM": "transports/voiture",
  "LEROY MERLIN VENISSIEUX": "shopping",
  "AMAZON EU SARL PARIS": "shopping",
  "LA FERME GSD VENOSC": "alimentation de base",
  "IF INVESTISSEMEN LES DEUX ALPE": "alimentation de base",
  "LA GUINGUETTE LES DEUX ALPE": "sorties resto/WE",
  "AGIP9961ISLE VOREPPE": "alimentation de base",
  "2THELOO NIMES NIMES": "transports/voiture",
  "M ET G SPORTS LES DEUX ALPE": "vacances/WE en famille",
  "RET DAB 08/08 LES DEUX ALPE": "shopping",
  "PRESSE LES DEUX ALPE": "vacances/WE en famille",
  "SHERPA MONT DE LANS": "alimentation de base",
  "EURL GINETTE L2 LES DEUX ALPE": "vacances/WE en famille",
  "MYRTILLES LES DEUX ALPE": "alimentation de base",
  "NOUNOU-TOP E14 9NN LO 7,98 EUR": "famille",
  "KLARNA*VARUSTE.N PARIS": "shopping",
  "RET DAB 05/08/24 LES DEUX ALPES": "vacances/WE en famille",
  "CYCL OLERON LA BREE LES B": "vacances/WE en famille",
  "JARDINS D AURELI LA BREE LES B": "alimentation de base",
  "VIR MENSUEL AOUT CHLOE": "virement interne",
  "LES GOURMANDISES ST GEORGES D O": "vacances/WE en famille",
  "LE JARDIN LA JO ST GEORGES D": "alimentation de base",
  "VIR VIREMENT AVEC FORTUNEO LIVRE": "épargne",
  "PECHERIES COTI ST PIERRE D O": "alimentation de base",
  "SNC BETTE BASTIE ST GEORGES D": "vacances/WE en famille",
  "AU GRE DU VENT ST GEORGES D": "vacances/WE en famille",
  "LES GOURMANDISES ST GEORGES D": "vacances/WE en famille",
  "ZOO LA PALMYRE LES MATHES": "vacances/WE en famille",
  "AVIA MERLINES": "alimentation de base",
  "MRS RA 401 VILLA LYON": "cantine",
  "VIR VIREMENT AVEC FORTUNEO LDDS": "épargne",
  "NETFLIX.COM LOS GATOS": "abonnements divertissements",
  "VIR VIREMENT BONNAV OLERON": "virement interne",
  "SWILE 561 RUE GEORGE": "cantine",
  "LPA LYON": "transports/voiture",
  "LES NUITS DE FOU LYON 5EME": "sorties resto/WE",
  "MIMO LYON": "sorties resto/WE",
  "CARREFOUR DAC VL BAGNOLS SUR C": "transports/voiture",
  "ALMA NEUILLY-SUR-SE": "shopping",
  "BABY JUNIOR BAGNOLS SUR C": "shopping",
  "RODRIGUEZ TRESQUES": "alimentation de base",
  "DECATHLON 0071 ST EGREVE": "shopping",
  "LA GAMELLE LYON": "sorties resto/WE",
  "VIR MENSUEL JUILLET": "virement interne",
  "ANN CARTE SNCF INTERNET PARIS 10": "transports/voiture",
  "LES ATELIERS LYON": "shopping",
  "RUE DUGUESCLIN LIMONEST": "shopping",
  "RET DAB 08/06 LYON MONTCHAT": "alimentation de base",
  "ALMA SNOWLEADER NEUILLY-SUR-S": "shopping",
  "AIRBNB * HMRQDPZ 318-488-4000": "sorties resto/WE",
  "VIR VIREMENT JUIN": "virement interne",
  "OL VALLEE ARENA DECINES CHARP": "sorties resto/WE",
  "3X 4X ONEY CROIX": "shopping",
  "MAISON DESCHAMPS LYON": "cantine",
  "HPY*VEEPEE LA PLAINE SAIN": "shopping",
  "LE POT COMMUN PARIS": "shopping",
  "TOTAL ORLEAT": "transports/voiture",
  "MAXICOFFEE GC DAUMESNIL": "transports/voiture",
  "ANN CARTE VEEPEE SAINT-DENIS": "shopping",
  "BOUCHERIE CHARCU LYON 3EME": "alimentation de base",
  "CARREFOUR MONTAG LES DEUX ALPE": "alimentation de base",
  "VIR MLLE LEA CAUCHARD": "shopping",
  "L ESPADON SAINT BONNET": "alimentation de base",
  "SEZANE PARIS": "shopping",
  "VIR MENSUEL MAI CHLOE": "virement interne",
  "LUNII SAS PARIS": "abonnements divertissements",
  "SC ALLEGRET SAV LAUDUN L ARDO": "alimentation de base",
  "INTERMARCHE VILLEURBANNE": "alimentation de base",
  "VIR FIN AVRIL": "virement interne",
  "LA TABACTIERE LYON EME": "shopping",
  "F COTISATION A UNE OFFRE D' ASSURANCE PERTE OU VOL": "assurances",
  "ENDURANCE CHRONO LE CAILAR": "sorties resto/WE",
  "VIR COMPLEMENT AVRIL": "virement interne",
  "VIR GOUJON CAUCHARD": "virement interne",
  "RATP PARIS": "transports/voiture",
  "VIR MENSUEL COURSES AVRIL CHLOE": "virement interne",
  "NEWREST WAGONS L PARIS": "sorties resto/WE",
  "VIR FIN MOIS": "virement interne",
  "BOTANIC SAINT PRIEST": "shopping",
  "VIR COURSES SUITE 2": "virement interne",
  "LYDIA APP PARIS": "sorties resto/WE",
  "DECLICLUDIK LYON LYON 3EME": "shopping",
  "VIR COURSES SUITE": "virement interne",
  "VIR APPRO COMPTE COMMUN": "virement interne",
  "MGP*VINTED PURC0 L-1125 LUXEMB": "shopping",
  "SNC ALLEGRE TRESQUES": "alimentation de base",
  "PETITSCULOTTES PARIS 8": "alimentation de base",
  "VIR YANN VERS CC MARS24": "virement interne",
  "SATA 2 ALPES LES DEUX ALPE": "vacances/WE en famille",
  "PRLV DEEZER SA": "abonnements divertissements",
  "LES COULEURS DU LYON 3EME": "shopping",
  "BYMYCAR LYON LYON EME": "transports/voiture",
  "BC COIFFURE LYON 9EME": "shopping",
  "ALMA NEUILLY-SUR-S": "shopping",
  "KLARNA PARIS": "shopping",
  "S A P LA PLAGNE TAR": "sorties resto/WE",
  "LES 4G GENAY": "cantine",
  "MGP*VINTED 81880 L-1125 LUXEMB": "shopping",
  "PHENECIA LYON": "sorties resto/WE",
  "KIABI BAGNOLS SUR C": "shopping",
  "LA POSTE.FR PARIS CEDEX 15": "shopping",
  "LA CARRETILLA ST GILLES": "sorties resto/WE",
  "QUIMPORTE LA SAI LYON 3EME": "shopping",
  "ASPHALTE.COM BORDEAUX": "shopping",
  "VIR DECEMBRE 2023": "virement interne",
  "S3A CAROMB": "vacances/WE en famille",
  "AMZN MKTP FR*HI7 AMAZON.FR": "shopping",
  "FOURNIL VIGNES THEIZE": "alimentation de base",
  "LA HALLE TONY GA LYON 7": "sorties resto/WE",
  "MGP*VINTED EXS 0 L-1125 LUXEMB": "shopping",
  "LA REDOUTE FR ROUBAIX": "shopping",
  "PRLV SARL M FIT CENTER": "abonnements sports",
  "ZARA LE PONTET": "shopping",
  "SHOEZ GALLERY LYON": "shopping",
  "MGP*VINTED 73610 L-1125 LUXEMB": "shopping",
  "S.L.T.C. LYON": "transports/voiture",
  "DOMAINE DU GOLF ST RAPHAEL": "sorties resto/WE",
  "ASS SPORT DANS L LYON": "shopping",
  "O KYPOS LYON 9EME": "cantine",
  "SHOP.EDWIN-EUROP WEIL AM RHEIN": "shopping",
  "PABLO ROMERO NIMES": "sorties resto/WE",
  "AMERICAN STEAKHO GONESSE": "sorties resto/WE",
  "COLLETTA CHARLIE LYON": "santé",
  "AREAS ROISSY ROISSY": "sorties resto/WE",
  "RELAY LYON": "sorties resto/WE",
  "RELAY ROISSY AERO C": "sorties resto/WE",
  "ERIC KAYSER AVIGNON": "alimentation de base",
  "LE TRAQUENARD LYON": "cantine",
  "L'ANTRELOU LES DEUX ALPE": "vacances/WE en famille",
  "SPL RU LYON": "transports/voiture",
  "RIE MANUTAN GONESSE CEDEX": "cantine",
  "MONOP DAILY LYON": "cantine",
  "GAEC L'ETOILE NO FELINES": "alimentation de base",
  "CENTRE ORL LAEN BRON": "santé",
  "BIPANDGO": "transports/voiture",
  "SERVICE NAVIGO PARIS 9": "transports/voiture",
  "A.R.E.A. 69671": "transports/voiture",
  "PERIPHERIQUE NOR CALUIRE ET CU": "transports/voiture",
  "GARAGE DES PINS LYON": "transports/voiture",
  "PRLV ACC DE: SOGECAP ID: FR04ZZZ110906 MOTIF:": "assurances",
  "PRELEVEMENT EUROPEEN DE: SWISSLIFE ID: FR49ZZZ808A3D MOTIF: SWISSL-10": "assurances",
  "OPENAI *CHATGPT DUBLIN": "abonnements divertissements",
  "GOOGLE ONE DUBLIN": "abonnements divertissements",
  "TOPWG.COM* E14 9NN LO 11,98 EUR": "famille",
  "NYX*AZDISTRIBUTI GONESSE": "shopping",
  "MONEY WALKIE SAINT-MANDE": "famille",
  "HELLO ASSO BEGLES": "famille",
  "IBIS GONESSE": "vacances/WE en famille",
  "MDP2A LES DEUX ALPE": "alimentation de base",
  "SLIDE PLANET THE LES DEUX ALPE": "vacances/WE en famille",
  "PRELEVEMENT EUROPEEN POUR CPTE DE:D.G.F.I.P. IMPOT 69015 ID: FR46ZZZ0": "virement interne",
  "PRELEVEMENT EUROPEEN POUR CPTE DE:D.G.F.I.P. IMPOT 38075 ID: FR46ZZZ0": "virement interne",
  "CHQ": "virement interne",
  "VIREMENT ???": "virement interne",
  "POLE CHEVAL ET A LIGNIERES": "vacances/WE en famille",
  "MALTING POT": "sorties resto/WE",
  "GARGAMELLE": "sorties resto/WE",
  "ARMADA": "sorties resto/WE",
  "BUVARD": "vacances/WE en famille",
  "TOPWG": "famille",
  "PAULDIS": "alimentation de base",
  "ANESTECIA": "santé",
  "SANERGI": "salaires",
  "MANUTAN INTERNATIONAL": "salaires",
  "SAS MULTI IMPACT": "assurances",
  "PRLV ACC DE: SOGECAP ID: FR": "épargne",
  "PRELEVEMENT EUROPEEN DE: SAS MULTI IMPA": "assurances",
  "ECHEANCE PRET N° CAPITAL AMORTI : 2 59": "prêts immo",
  "ECHEANCE PRET N° CAPITAL AMORTI : 457,": "prêts immo",
  "CHEQUE 17": "famille",
  "CHEQUE 18": "transports/voiture",
  "VIR INSTANTANE EMIS LOGITEL POUR: RAMOS ALM": "ménage",
  "VIR INSTANTANE EMIS LOGITEL POUR: MJC MONTC": "famille",
  "VIR MENSUEL CHLOE": "salaires",
  "AUTOGRILL FFH AU L ISLE D ABEA": "sorties resto/WE",
  "IMPRIMERIE NATIO PARIS": "famille",
  "REVOLUT**5570* PARIS": "shopping",
  "EARL GIGANDON SAINT DENIS S": "alimentation de base",
  "VIR INSTANTANE EMIS LOGITEL POUR: LEA MOUDI": "famille",
  "GL BRON BRON": "shopping",
  "AREAS A72 HFOREZ LES SALLES": "vacances/WE en famille",
  "NALOU LYON LYON": "shopping",
  "ALLIER DOYET DOYET": "vacances/WE en famille",
  "S CONTACT CARREF LIGNIERES": "vacances/WE en famille",
  "VIR M JEAN MARIE CAUCHARD": "shopping",
  "VIR MANUTAN INTERNATIONAL": "salaires",
  "ON PARTICIPE ASNIERES SUR S": "shopping",
  "LE MIRADOR MANOSQUE": "cantine",
  "VIR GENERATION": "santé",
  "VIR MANGOPAY": "shopping",
  "PRELEVEMENT EUROPEEN POUR CPTE DE:D.G.F": "factures énergie/eau",
  "VIR WERO WERO HELENE LITHAR": "vacances/WE en famille",
  "RET DAB 15/05/26 CHA_MEZE_DU_GEN": "vacances/WE en famille",
  "RET DAB 14/05/26 MEZE": "vacances/WE en famille",
  "POINT P BMRA VILLEURBANNE": "courses non essentielles",
  "BOTANICSTPRIEST SAINT PRIEST": "courses non essentielles",
  "JT MONTCHAT LYON": "sorties resto/WE",
  "UBR* PENDING.UBE AMSTERDAM": "sorties resto/WE",
  "PRLV AXA ASSURANCES IARD MUTUELL": "assurances",
  "PRLV AXA ASSURANCES VIE MUTUELLE": "assurances",
  "TOPWG.COM* LONDON 11,98 EUR": "famille",
  "ECHEANCE PRET N° CAPITAL AMORTI : 2 58": "prêts immo",
  "ECHEANCE PRET N° CAPITAL AMORTI : 455,": "prêts immo",
  "VIR RECU 3483570899S DE: CAF DU RHONE MOTIF: 41": "salaires",
  "VIR PRIME CHLOE": "épargne",
  "GL LYON LYON 3EME": "shopping",
  "NINTENDO CA16220 FRANKFURT AM": "abonnements divertissements",
  "BAM BEAUMONT-MONT": "cantine",
  "ABC PAYS DAIX TA AIX EN PROVEN": "cantine",
  "LE LOCAL BOUC BEL AIR": "cantine",
  "EVANESSA CABRIES": "cantine",
  "LE BABYLONE BRIVES CHAREN": "cantine",
  "HPY*VEEPEE LA PLAINE SAI": "salaires",
  "CALAO 160 LE BOURG D'OI": "alimentation de base",
  "CAB NICE": "cantine",
  "AREAS NICE NICE": "cantine",
  "KALLISTE NICE": "cantine",
  "CHEZ LES AMIS OLLIOULES": "cantine",
  "LE TONO NICE": "cantine",
  "SUMUP *BENEZET LE PRADET": "cantine",
  "CREMERIE ALPES LES DEUX ALPE": "vacances/WE en famille",
  "COMMUNE LES DEUX LES DEUX ALPE": "vacances/WE en famille",
  "M G SPORTS LES DEUX ALPE": "alimentation de base",
  "KANATA LES DEUX ALPE": "vacances/WE en famille",
  "SAS LHASSA LES DEUX ALPE": "alimentation de base",
  "SATA 2 ALPES INT LES DEUX ALPES": "vacances/WE en famille",
  "CENTRE MED 2 ALP LES DEUX ALPE": "alimentation de base",
  "PHARMA DU GLACI LES DEUX ALPE": "vacances/WE en famille",
  "DECATHLON 0023 ECHIROLLES": "abonnements sports",
  "BOULANGER ECHIROLLES": "shopping",
  "MOL*CAB MED": "alimentation de base",
  "ESAT LES ETANGS PORT DE BOUC": "cantine",
  "TRATTINO LYON": "cantine",
  "HPY*PHOTOWEB SAINT-EGREVE": "shopping",
  "SARL TRESACOIS CONNAUX": "alimentation de base",
  "ECHEANCE PRET N° CAPITAL AMORTI : 454,": "prêts immo",
  "VIR RECU 0296258058S DE: CAF DU RHONE MOTIF: 41": "salaires",
  "THE RUCK HOTEL LYON 7EME": "vacances/WE en famille",
  "LA PETRIE LYON": "cantine",
  "MY SELLING TOOLS 92 BOULOGNE-BI": "shopping",
  "HOTEL MERCURE NANTES": "vacances/WE en famille",
  "MNA TAXI ST HERBLAIN": "transports/voiture",
  "AREAS NANTES NANTES": "cantine",
  "NEWREST WAGONS-L PARIS": "cantine",
  "LA BACLERIE NANTES": "cantine",
  "VIR LEA CAUCHARD": "shopping",
  "GBC MONTAGNE BOURG ST MAU": "sorties resto/WE",
  "CUISINE BRISON NANTES": "cantine",
  "CELLERIER HALLE LYON": "alimentation de base",
  "EDEN ROCK CAFE LYON": "sorties resto/WE",
  "RET DAB 28/03/26 LYON 2EME": "alimentation de base",
  "RACINE RESTAURAN LYON": "cantine",
  "SP LA TRIBU HAPP ARTANNES-SUR-": "sorties resto/WE",
  "VIR CONCERT TELLIER": "abonnements divertissements",
  "CALAO 53 LYON 7E ARRON": "alimentation de base",
  "PANEO BRON": "alimentation de base",
  "SELARL DR LAZAR LYON": "santé",
  "ECHEANCE PRET N° CAPITAL AMORTI : 453,": "prêts immo",
  "VIR RECU 6390929621S DE: CAF DU RHONE MOTIF: 41": "salaires",
  "SEPHORA SA SARAN": "shopping",
  "DMA LYON": "shopping",
  "DECATHLON BEYNOS 0427 BEYNOST/": "abonnements sports",
  "GRAND FRAIS BRON": "alimentation de base",
  "ONDET CHRISTIAN ATTIGNAT": "alimentation de base",
  "SUMUP *GOBYGREE TOULOUSE": "cantine",
  "LE MOULIN DES TO TOULOUSE": "cantine",
  "RELAY TOULOUSE": "cantine",
  "LA-CARTOUCHERIE TOULOUSE": "cantine",
  "SQ *LA COTE DE B TOULOUSE": "cantine",
  "THE HOPSCOTCH TOULOUSE": "cantine",
  "YBUECZ8HCHXJ TIS TOULOUSE CEDE": "cantine",
  "MARIE BLACHERE BAGNOLS SUR C": "alimentation de base",
  "CB-BILLETWEB 75007 PARIS": "sorties resto/WE",
  "SAS LASOUL LYON": "sorties resto/WE",
  "TABLE DE MAX BOE LYON": "sorties resto/WE",
  "BURGER KING VALENCE": "sorties resto/WE",
  "JACQUES SPORTS LES DEUX ALPE": "vacances/WE en famille",
  "DJC DISTRIBUTION RIANS": "alimentation de base",
  "SMALLABLE PARIS": "shopping",
  "VIR INTEREPARGNE": "salaires",
  "SYNDICAT LOCAL LES DEUX ALPES": "vacances/WE en famille",
  "LIBRAIRIE DE LA LYON": "shopping",
  "ECHEANCE PRET N° CAPITAL AMORTI : 451,": "prêts immo",
  "VIR RECU 3594099591S DE: CAF DU RHONE MOTIF: 41": "salaires",
  "DECATHLON BRON BRON": "abonnements sports",
  "GDE PHARMA LYON LYON": "santé",
  "BRASSERIE RIVES LYON": "sorties resto/WE",
  "RET DAB 20/01/26 LYON MONTCHAT": "shopping",
  "SP LA BELLE BOUC LYON": "courses non essentielles",
  "FOURNIL DES GIRO LYON": "cantine",
  "ECHEANCE PRET N° CAPITAL AMORTI : 2 57": "prêts immo",
  "ECHEANCE PRET N° CAPITAL AMORTI : 450,": "prêts immo",
  "VIR EUROPEEN EMIS LOGITEL POUR: MJC MONTC": "famille",
  "VIR RECU 0295623191S DE: CAF DU RHONE MOTIF: 41": "salaires",
  "VIR CHAMBRE ENFANTS": "shopping",
  "BOUCHERIE BELIN LYON": "alimentation de base",
  "MIRAL LYON": "alimentation de base",
  "RET DAB 16/12/24 LYON": "alimentation de base",
  "L'ODYSSEE DES CO LYON": "shopping",
  "VIR M. ET MME BONNAVENTURE": "vacances/WE en famille",
  "SUMUP *MY CATER LYON": "alimentation de base",
  "MAXALANDRE CHARBONNIERES": "alimentation de base",
  "RET DAB 02/07/24 LYON": "alimentation de base",
  "SEPHORA": "shopping",
  "IKKS RETAIL": "shopping",
  "IKKS": "shopping",
  "BOBBIES": "shopping",
  "CALZDEONIA": "shopping",
  "CALZEDONIA": "shopping",
  "ZELYS": "shopping",
  "NET PHOTO": "shopping",
  "TOPWEB": "shopping",
  "UTILE & AGREABLE": "shopping",
  "AUTOUR DU MONDE": "shopping",
  "ZETTLE_*FLOWRETT": "shopping",
  "FLOWRETT": "shopping",
  "AREAS": "sorties resto/WE",
  "LA PETIRE": "sorties resto/WE",
  "ROCAMBOLE": "sorties resto/WE",
  "SUNDAY*CARMELO": "sorties resto/WE",
  "CARMELO": "sorties resto/WE",
  "GOODWIN BREWERY": "sorties resto/WE",
  "L'UISSAN": "sorties resto/WE",
  "O GALETTES": "sorties resto/WE",
  "JEAN DE PARIS": "sorties resto/WE",
  "RTM MARSEILLE": "transports/voiture",
  "GARE PART DIEU": "transports/voiture",
  "DAC VL": "transports/voiture",
  "DEKRA-NORISKO": "transports/voiture",
  "DEKRA": "transports/voiture",
  "NORISKO": "transports/voiture",
  "CGF15908": "transports/voiture",
  "VALRHONA": "courses non essentielles",
  "MEERT": "courses non essentielles",
  "CULTURA": "courses non essentielles",
  "K FAMMILY": "vacances/WE en famille",
  "HOSTELLERIE PEROUGES": "vacances/WE en famille",
  "VERTBAUDET": "famille",
  "SUMUP  *MELISSA": "santé",
  "SUMUP *MELISSA": "santé",
  "PHOTOMATON": "ménage",
  "D.G.F.I.P": "ménage",
  "DGFIP": "ménage",
  "SAMSE": "travaux/jardin",
  "POINT P ": "travaux/jardin",
  "POINT P	": "travaux/jardin",
  "POINT P BMRA": "travaux/jardin",
  "BOTANIC": "travaux/jardin",
  "BOTANICSTPRIEST": "travaux/jardin",
  "BARTHELEMY BOIS": "travaux/jardin",
  "BARTHÉLEMY BOIS": "travaux/jardin",
  "QUIETIS": "assurances",
  "INTERETS DEBITEURS": "frais bancaires",
  "ARRETE TRIMESTRIEL": "frais bancaires",
  "REGUL. OPERATION": "prêts immo",
  "LBC FRANCE SAS": "remboursements",
  "LBC FRANCE": "remboursements",
  "MANGOPAY": "remboursements",
  "LYDIA*LYDIA": "virement interne",
  "LYDIA SOLU": "virement interne",
  "GOUJON/CAUCHARD": "virement interne",
  "GOUJON CAUCHARD": "virement interne",
  "INTERSPORT": "abonnements sports",
  "EKOSPORT": "abonnements sports",
  "NEXTORY": "abonnements divertissements",
  "LEVIS ONLINE": "shopping",
  "LEVIS": "shopping",
  "FOOT LOCKER": "shopping",
  "DISTRI DRH": "shopping",
  "PAUL & NANY": "shopping",
  "SAS LES POSETTES": "vacances/WE en famille",
  "CASTILLAN LA GRAVE": "vacances/WE en famille",
  "CASA BATLLO": "vacances/WE en famille",
  "CHATEAU MUZELLE": "vacances/WE en famille",
  "LOSTERIA": "sorties resto/WE",
  "LE FEUNARD": "sorties resto/WE",
  "GOLDEN TEMPLE": "sorties resto/WE",
  "L EQUILIBRISTE": "sorties resto/WE",
  "YURPLAN": "sorties resto/WE",
  "SPODE LYON": "sorties resto/WE",
  "SUMUP  *GARGAMEL": "sorties resto/WE",
  "DAC ESSO": "transports/voiture",
  "AREA NFC": "transports/voiture",
  "AGIP9348": "transports/voiture",
  "T147 BADALONA": "transports/voiture",
  "DR PUENTEDURA": "santé",
  "SUMUP  *CENTRE L DECINES": "santé",
  "PAUL LYON": "alimentation de base",
  "ECRINS DOUCEUR": "alimentation de base",
  "LE FROM PARIS": "alimentation de base",
  "CERISE ET POTIRO": "alimentation de base",
  "XARCUTERIES SAMA": "alimentation de base",
  "AUTOUR DU BEBE": "famille",
  "BMRA CHAMBERY": "travaux/jardin",
  "MICRO SILLON": "courses non essentielles",
  "SUMUP  *ATHLETES": "abonnements sports",
  "CF AVE SAN": "vacances/WE en famille",
  "ZENITH BRUNCH": "vacances/WE en famille",
  "CANSALADERIA": "vacances/WE en famille",
  "SANDWICHEZ": "vacances/WE en famille",
  "EL NACIONAL": "vacances/WE en famille",
  "LA PALLARESA": "vacances/WE en famille",
  "CASA ALFONSO": "vacances/WE en famille",
  "CABESTAN": "travaux/jardin",
};

export const KW_RULES: { kw: string[]; cat: string }[] = [
  { kw: ['CARREFOUR','LECLERC','INTERMARCHE','LIDL','ALDI','MONOPRIX','FRANPRIX','CASINO ','AUCHAN','BIOCOOP','NATURALIA','PICARD','GRAND FRAIS','SUPER U','BOULANGERIE','BOUCHERIE','PRIMEUR','EPICERIE','SPAR ','CORA ','NETTO ','MATCH ','LEADER PRICE','SUPER BIO','FERME','MARCHE ','CASINO','PATISSERIE','FROMAGERIE','SUPERMARCHE','TERRES','LYONNAISE','JARI','THURINS','MAISON','GIRAUD','NEUVILLE','VALERIE','THEILLER','JACQU','SURGELES','NAVARRO','MEYZIEU','STEPHANE','MARCEL','SAVEURS','COLOMBIER','VESSIERE','MONTCH','VENOSC','BALL','PAULDIS'], cat: 'alimentation de base' },
  { kw: ['TOTALENERGIE','TOTAL ENERGIE','SHELL','ESSO','RATP','SNCF','TRANSILIEN','OUIGO','NAVIGO','VELIB','UBER','BOLT','TAXI','BIP&GO','BIPANDGO','VINCI','SANEF','ESCOTA','AUTOROUTE','PARKING','STATION ESSENCE','STATION SERVICE','CARBURANT','SUPERETHANOL','KEOLIS','TRENITALIA','EUROSTAR','PEAGE','BLABLACAR','TRAM','AMSTERDAM','DOTT','SCOOTER','STATION','AVIA','INTERNET','TOTAL','PONT','THELOO','MONTCYCLE','RENNES'], cat: 'transports/voiture' },
  { kw: ['AXA','MAIF','MACIF','MATMUT','GMF','ALLIANZ','SWISS LIFE','SWISSLIFE','SOGESSUR','LUKO','APRIL','GENERALI','GROUPAMA','MMA ','PREVOYANCE','ASSURANCE','MUTUELLE','MAF ','COVEA','IMPACT','SOGECAP','SAS MULTI IMPACT'], cat: 'assurances' },
  { kw: ['CREDIT FONCIER','CREDIT IMMOB','PRET IMMO','ECHEANCE PRET','REMB PRET','CREDIT IMMO','ECHEANCE IMMO','IMMO'], cat: 'prêts immo' },
  { kw: ['EDF','ENGIE','DIRECT ENERGIE','ILEK','PLANETE OUI','VEOLIA','SAUR','SUEZ','EAU DE PARIS','ELECTRICITE','GAZ DE FRANCE','TOTAL GAZ','ENEDIS','GRDF','TOTAL','GRAND','CLIENTS','PARTICULIERS','GENERALE','FINA','DIRECTION'], cat: 'factures énergie/eau' },
  { kw: ['PHARMACIE','MEDECIN','DR ','DENTISTE','HOPITAL','CLINIQUE','OPTICIEN','OPTIQUE','KINE','OSTEO','PSYCHO','INFIRM','LABORATOIRE','RADIOLOGIE','SCANNER','CPAM','AMELI','MEDECINE','PHARMACI','DOCTEUR','CABINET','KINESITH','LAURENT','DAUTRIA','DANTEC','PHIE','MEDICINA','GESTION','FONTAINES','CHARMILLES','ANESTECIA'], cat: 'santé' },
  { kw: ['MONEY WALKIE','MONEYWALKIE','CRECHE','GARDERIE','NOURRICE','BABYSIT','AU PAIR','ASSISTANTE MATERNELLE','ASSMAT','NOUNOU','URSSAF','CESU','MJC','KINOUGARDE','SCOLARITE','VILLE','NATH','SCOL','REST','TOPWG','WERO WERO'], cat: 'famille' },
  { kw: ['CANTINE','RESTAURATION SCOLAIRE','TICKET RESTO','TITRES RESTO','SWILE','TITRES RESTAURANT','DESCHAMPS','BISTROT','BERTHET','GEORGE','GENAY'], cat: 'cantine' },
  { kw: ['FORTUNEO','FRAIS BANCAIRE','COTISATION CARTE','AGIOS','INTERETS DEBIT','FRAIS BANCAIRES','ANTARIUS','COMMISSION','FRAIS','INSTANTANE','ELEC'], cat: 'frais bancaires' },
  { kw: ['IKEA','LEROY MERLIN','CASTORAMA','BRICOMARCHE','BRICORAMA','BRICODEPOT','BUT ','MAISON DU MONDE','HABITAT ','JARDINERIE','TRUFFAUT','GAMM VERT','PAIEMENT','ROSA'], cat: 'ménage' },
  { kw: ['RESTAURANT','BRASSERIE','BISTROT','BISTRO','PIZZA','KEBAB','SUSHI','BURGER','MCDONALDS','KFC','QUICK ','SUBWAY','DOMINOS','DELIVEROO','UBER EATS','JUST EAT','BAR ','PUB ','TAVERNE','AUBERGE','CREPERIE','TRATTORIA','PIZZERIA','CINEMA','THEATRE','BOWLING','MONTREAL','PLAGNE','WEEKEND','ANNECY','DORVAL','FLEXITARIEN','DOMAINE','GILLES','CARRETILLA','HALLE','TONY','MALTING POT','GARGAMELLE','ARMADA LYON'], cat: 'sorties resto/WE' },
  { kw: ['ZARA','H&M','PRIMARK','UNIQLO','GAP ','MANGO','AMAZON','CDISCOUNT','FNAC','DARTY','BOULANGER','APPLE STORE','SAMSUNG','VINTED','LEBONCOIN','SHEIN','ASOS','ZALANDO','KIABI','SEPHORA','MARIONNAUD','NOCIBE','PARFUMERIE','SPORT 2000','GO SPORT','VEEPEE','DECATHLON','BERSHKA','IKEA','LEROY','COULEURS','LUXEMB','VILNIUS','KLARNA','MKTP','AMZN','REDOUTE','ROUBAIX','NEUILLY','DECLICLUDIK','ALMA','POSTE','NOEL','ENCHANTEMENT','JOUET','SEZANE','ASPHALTE','PAYMENTS','DUGUESCLIN','LIMONEST','KING','LEVIS','FOOT LOCKER'], cat: 'shopping' },
  { kw: ['BOOKING','AIRBNB','ABRITEL','GITE ','HOTEL','CAMPING','CLUB MED','TUI ','VOYAGE','VACANCES','EASYJET','RYANAIR','AIR FRANCE','VUELING','TRANSAVIA','CORSAIR','AEROPORT','AIRPORT','ALPES','SPORTS','CAROMB','GOURMANDISES','PRESSE','MATHES','PALMYRE','VERCO','SYNDICAT','LOCAL','VENT','BUVARD'], cat: 'vacances/WE en famille' },
  { kw: ['DECATHLON','BASIC FIT','BASIC-FIT','FITNESS','SALLE DE SPORT','COACHING','TENNIS','NATATION','PISCINE','YOGA','PILATES','CROSSFIT','CENTER'], cat: 'abonnements sports' },
  { kw: ['NETFLIX','SPOTIFY','DISNEY+','DISNEY PLUS','APPLE TV','AMAZON PRIME','CANAL+','CANAL PLUS','DEEZER','YOUTUBE','TWITCH','STEAM','PLAYSTATION','XBOX','NINTENDO','CINEMA','THEATRE','CONCERT','DISNEYLAND','LEGO','APPLE','DISNEY','CANAL','PRIME','HULU','LUNII','PLAYBAC','FREE','ORANGE','BOUYGUES','SFR','ITUNES','DEEZERFR','CORK','NEXTORY','BITWARDEN'], cat: 'abonnements divertissements' },
  { kw: ['ASSURANCE VIE','LDDS','LIVRET A','LIVRET ','PEL ','PEA ','EPARGNE','PLACEMENT','LIVRET','ASSURANCE','SUZANNE','JEANNE','GASPARD'], cat: 'épargne' },
  { kw: ['VIREMENT RECU','VIREMENT EN VOTRE FAVEUR'], cat: 'remboursements' },
  { kw: ['CAF ','ALLOCATIONS FAMILIALES','AIDE AU LOGEMENT','APL '], cat: 'CAF' },
  { kw: ['CASTORAMA','LEROY MERLIN','BRICO DEPOT','BRICO MARCHE','POINT P','SAMSE','BOTANIC','JARDILAND','TRUFFAUT','GAMM VERT','VILLAVERDE','BRICORAMA','MR BRICOLAGE','ACE QUINCAILLERIE','LAPEYRE','SAINT-MACLOU','BECARRE','BARTHELEMY BOIS','BARTHÉLEMY BOIS','CABESTAN','BMRA'], cat: 'travaux/jardin' },
];
