import { MacroCategory } from './types';

export const MACROS: Record<MacroCategory, { color: string; cls: string }> = {
  Besoins:             { color: '#3B82F6', cls: 'b-B' },
  Envies:              { color: '#F59E0B', cls: 'b-E' },
  Épargne:             { color: '#10B981', cls: 'b-Ep' },
  Revenus:             { color: '#8B5CF6', cls: 'b-R' },
  'Virements internes':{ color: '#64748B', cls: 'b-VI' },
  'Non classé':        { color: '#6B7280', cls: 'b-N' },
};

export const SUBS: Record<string, string[]> = {
  Besoins:  ['alimentation de base','transports/voiture','assurances','prêts immo','factures énergie/eau','santé','famille','cantine','frais bancaires','ménage','frais notaire'],
  Envies:   ['sorties resto/WE','shopping','vacances/WE en famille','abonnements sports','abonnements divertissements','courses non essentielles'],
  Épargne:  ['épargne'],
  Revenus:  ['salaires','remboursements','CAF'],
  'Virements internes': ['virement interne'],
};

export const SUB2MACRO: Record<string, MacroCategory> = {};
Object.entries(SUBS).forEach(([m, ss]) =>
  ss.forEach(s => (SUB2MACRO[s] = m as MacroCategory))
);

export const ALL_SUBS = Object.values(SUBS).flat();

export const ACCOUNT_COLORS: Record<string, string> = {
  'CB Yann':                '#3B82F6',
  'CB Chloé':               '#EC4899',
  'Compte commun Fortuneo': '#10B981',
  'Compte SG':              '#F59E0B',
};

export const MERCHANT_RULES: Record<string, string> = {
  "PLAYBAC": "abonnements divertissements",
  "IMPÔTS": "frais bancaires",
  "BIP & GO": "transports/voiture",
  "ALLIANZ I A R D ALLIANZ I A R D": "assurances",
  "ANTARIUS": "frais bancaires",
  "MULT IMPACT": "assurances",
  "GC RE LUKO COVER": "assurances",
  "CLIMYM MAINTENANCE 10 03": "factures énergie/eau",
  "ALEXIS LELOUCY 10 03": "vacances/WE en famille",
  "FREE": "abonnements divertissements",
  "PAJEMPLOI": "salaires",
  "PRÊT IMMO": "prêts immo",
  "SOGESSUR": "assurances",
  "PAIEMENT ROSA": "ménage",
  "ASSMAT": "famille",
  "CAF DU RHONE": "salaires",
  "EAU DU GRAND LYON": "factures énergie/eau",
  "URSSAF CESU": "ménage",
  "SFR": "abonnements divertissements",
  "ALLIANZ": "assurances",
  "LUKO": "assurances",
  "SUEZ EAU FRANCE SAS-SUEZ EAU FRANCE": "factures énergie/eau",
  "CRECHE": "famille",
  "DEEZERFR": "abonnements divertissements",
  "APPLE.COM/BILL": "abonnements divertissements",
  "TCL LYON": "transports/voiture",
  "NETFLIX.COM": "abonnements divertissements",
  "CAMIEG": "santé",
  "EDF CLIENTS PARTICULIERS": "factures énergie/eau",
  "ASSURANCE VIE SUZANNE": "épargne",
  "ASSURANCE VIE JEANNE": "épargne",
  "ASSURANCE VIE GASPARD": "épargne",
  "SWILE": "cantine",
  "AMAZON PAYMENTS": "shopping",
  "SNCF": "transports/voiture",
  "IKEA": "ménage",
  "AXA FRANCE": "santé",
  "AXA ASS VIE": "santé",
  "MUTUELLE AXA": "santé",
  "ENERGIE MUTUELLE": "santé",
  "CPAM": "santé",
  "VIREMENT AVEC FORTUNEO LDDS": "épargne",
  "VIREMENT AVEC FORTUNEO LIVRE": "épargne",
  "VIREMENT EPARGNE LDDS": "épargne",
  "AMAZON PRIME": "abonnements divertissements",
  "NETFLIX COM": "abonnements divertissements",
  "DEEZER SA": "abonnements divertissements",
  "PRIME VIDEO": "abonnements divertissements",
  "LUNII SAS": "abonnements divertissements",
  "BITWARDEN": "abonnements divertissements",
  "TENACY": "salaires",
  "RTE RESEAU DE TRANSPORT D EL": "salaires",
  "DGFIP FINANCES PUBLIQUES": "salaires",
  "EPARGNE": "épargne",
  "REVOLUT": "épargne",
  "SOLDE REGLEMENTAIRE LIVRET A": "épargne",
  "VERSEMENT INITIAL LDD": "épargne",
  "REMBOURSEMENT VACANCES": "épargne",
  "REMBOURSEMENT CANADA": "épargne",
  "DIRECTION GENERALE DES FINA": "factures énergie/eau",
  "EDF CLT PART": "factures énergie/eau",
  "EAU GRAND LYON": "factures énergie/eau",
  "ENTRETIEN POMPE A CHAL": "factures énergie/eau",
  "ECHEANCE PRET": "prêts immo",
  "RECU DE: SARL NOTAIRES FOCH": "frais notaire",
  "NOTAIRES DBTB": "frais notaire",
  "FRAIS VIREMENT": "frais bancaires",
  "COTISATION QUIETIS": "frais bancaires",
  "TIMBRE FISCAL": "frais bancaires",
  "F COTISATION A UNE OFFRE D ASSURANCE": "assurances",
  "URSSAF": "famille",
  "KINOUGARDE": "famille",
  "MJC": "famille",
  "VILLE DE LYON": "famille",
  "SIGPAS": "famille",
  "REST SCOL CB NET": "famille",
  "GOUJON CHLOE": "famille",
  "NATH BOUDON": "famille",
  "SOLDE TOUS COMPTES NATH": "famille",
  "TOP-ASSMAT": "famille",
  "TOP ASSMAT": "famille",
  "NOUNOU-TOP": "famille",
  "SJR LABELS": "famille",
  "LUMYS PHOTO": "famille",
  "AMAZON EU SARL": "shopping",
  "AMZN MKTP FR": "shopping",
  "AMAZON.FR": "shopping",
  "VINTED": "shopping",
  "LEBONCOIN": "shopping",
  "VEEPEE": "shopping",
  "KLARNA": "shopping",
  "LA REDOUTE": "shopping",
  "DECATHLON": "shopping",
  "FNAC": "shopping",
  "LEROY MERLIN": "ménage",
  "CASTORAMA": "shopping",
  "IKKS PARIS": "shopping",
  "SEZANE": "shopping",
  "ASPHALTE": "shopping",
  "PICARD SURGELES": "alimentation de base",
  "LA VIE CLAIRE": "alimentation de base",
  "LIDL": "alimentation de base",
  "INTERMARCHE": "alimentation de base",
  "AUCHAN": "alimentation de base",
  "CARREFOUR": "alimentation de base",
  "MONOPRIX": "shopping",
  "UBER *TRIP": "transports/voiture",
  "DOTT SCOOTER": "transports/voiture",
  "RATP": "transports/voiture",
  "KEOLIS LYON": "transports/voiture",
  "SPL MOBILITES": "transports/voiture",
  "3X 4X ONEY": "transports/voiture",
  "TRAINLINE": "vacances/WE en famille",
  "AIRBNB": "vacances/WE en famille",
  "AIR CAN": "vacances/WE en famille",
  "BOOKING": "vacances/WE en famille",
  "SARL M FIT CENTER": "abonnements sports",
  "CROSSIFT": "abonnements sports",
};

export const KW_RULES: { kw: string[]; cat: string }[] = [
  { kw: ['CARREFOUR','LECLERC','INTERMARCHE','LIDL','ALDI','MONOPRIX','FRANPRIX','CASINO ','AUCHAN','BIOCOOP','NATURALIA','PICARD','GRAND FRAIS','SUPER U','BOULANGERIE','BOUCHERIE','PRIMEUR','EPICERIE','SPAR ','CORA ','NETTO ','MATCH ','LEADER PRICE','SUPER BIO','FERME','MARCHE '], cat: 'alimentation de base' },
  { kw: ['TOTALENERGIE','TOTAL ENERGIE','SHELL','ESSO','RATP','SNCF','TRANSILIEN','OUIGO','NAVIGO','VELIB','UBER','BOLT','TAXI','BIP&GO','BIPANDGO','VINCI','SANEF','ESCOTA','AUTOROUTE','PARKING','STATION ESSENCE','STATION SERVICE','CARBURANT','SUPERETHANOL'], cat: 'transports/voiture' },
  { kw: ['AXA','MAIF','MACIF','MATMUT','GMF','ALLIANZ','SWISS LIFE','SWISSLIFE','SOGESSUR','LUKO','APRIL','GENERALI','GROUPAMA','MMA ','PREVOYANCE','ASSURANCE','MUTUELLE','MAF '], cat: 'assurances' },
  { kw: ['CREDIT FONCIER','CREDIT IMMOB','PRET IMMO','ECHEANCE PRET','REMB PRET'], cat: 'prêts immo' },
  { kw: ['EDF','ENGIE','DIRECT ENERGIE','ILEK','PLANETE OUI','VEOLIA','SAUR','SUEZ','EAU DE PARIS','ELECTRICITE','GAZ DE FRANCE','TOTAL GAZ'], cat: 'factures énergie/eau' },
  { kw: ['PHARMACIE','MEDECIN','DR ','DENTISTE','HOPITAL','CLINIQUE','OPTICIEN','OPTIQUE','KINE','OSTEO','PSYCHO','INFIRM','LABORATOIRE','RADIOLOGIE','SCANNER','CPAM','AMELI','MEDECINE'], cat: 'santé' },
  { kw: ['MONEY WALKIE','MONEYWALKIE','CRECHE','GARDERIE','NOURRICE','BABYSIT','AU PAIR','ASSISTANTE MATERNELLE'], cat: 'famille' },
  { kw: ['CANTINE','RESTAURATION SCOLAIRE','TICKET RESTO','TITRES RESTO'], cat: 'cantine' },
  { kw: ['FORTUNEO','FRAIS BANCAIRE','COTISATION CARTE','AGIOS','INTERETS DEBIT'], cat: 'frais bancaires' },
  { kw: ['IKEA','LEROY MERLIN','CASTORAMA','BRICOMARCHE','BRICORAMA','BRICODEPOT','BUT ','MAISON DU MONDE','HABITAT ','JARDINERIE','TRUFFAUT','GAMM VERT'], cat: 'ménage' },
  { kw: ['RESTAURANT','BRASSERIE','BISTROT','BISTRO','PIZZA','KEBAB','SUSHI','BURGER','MCDONALDS','KFC','QUICK ','SUBWAY','DOMINOS','DELIVEROO','UBER EATS','JUST EAT','BAR ','PUB ','TAVERNE','AUBERGE','CREPERIE'], cat: 'sorties resto/WE' },
  { kw: ['ZARA','H&M','PRIMARK','UNIQLO','GAP ','MANGO','AMAZON','CDISCOUNT','FNAC','DARTY','BOULANGER','APPLE STORE','SAMSUNG','VINTED','LEBONCOIN','SHEIN','ASOS','ZALANDO','KIABI','SEPHORA','MARIONNAUD','NOCIBE','PARFUMERIE','SPORT 2000','GO SPORT'], cat: 'shopping' },
  { kw: ['BOOKING','AIRBNB','ABRITEL','GITE ','HOTEL','CAMPING','CLUB MED','TUI ','VOYAGE','VACANCES','EASYJET','RYANAIR','AIR FRANCE','VUELING','TRANSAVIA','CORSAIR','AEROPORT','AIRPORT'], cat: 'vacances/WE en famille' },
  { kw: ['DECATHLON','BASIC FIT','BASIC-FIT','FITNESS','SALLE DE SPORT','COACHING','TENNIS','NATATION','PISCINE','YOGA','PILATES','CROSSFIT'], cat: 'abonnements sports' },
  { kw: ['NETFLIX','SPOTIFY','DISNEY+','DISNEY PLUS','APPLE TV','AMAZON PRIME','CANAL+','CANAL PLUS','DEEZER','YOUTUBE','TWITCH','STEAM','PLAYSTATION','XBOX','NINTENDO','CINEMA','THEATRE','CONCERT','DISNEYLAND','LEGO'], cat: 'abonnements divertissements' },
  { kw: ['ASSURANCE VIE','LDDS','LIVRET A','LIVRET ','PEL ','PEA ','EPARGNE','PLACEMENT'], cat: 'épargne' },
  { kw: ['VIREMENT RECU','VIREMENT EN VOTRE FAVEUR'], cat: 'remboursements' },
  { kw: ['CAF ','ALLOCATIONS FAMILIALES','AIDE AU LOGEMENT','APL '], cat: 'CAF' },
];
